create table if not exists public.submissions (
    id bigint generated by default as identity primary key,
    name text not null,
    contact text not null,
    message text not null,
    created_at timestamptz not null default timezone('utc', now())
);

alter table public.submissions enable row level security;
